### ISSUE TITLE
Required parameters not enforced

### ISSUE THREAD

**Issue by cfoley-heila** [aQute-os/biz.aQute.openapi#8]
1. **If a query parameter is specified as required**, a request that is missing that parameter is accepted; the implementation code receives a null value. E.g.:
For path: `/site/testquerySingle` with parameter specification
`{ "name": "qpsingle",
"in": "query",
"required": true,
"type": "string"
}`
A request: `http://..../site/testquerySingle` is accepted; the implementation's `String qpsingle` is received as null, and the response is HTTP 200.

2. **If a body parameter is specified as required**, a request that includes no payload receives HTTP 500 response.

**In both cases, the response should be HTTP 4xx - perhaps 422, but at least 400.**

**Comment by pkriens** [comment]
I've just build 1.8.0-SNAPSHOT with an update.

Please be aware that code that worked might now get a 400 response ... 

Please give some feedback if this works as desired.
