### ISSUE TITLE
Consistency issue not reported properly by generation task

### ISSUE THREAD

**Issue by cfoley-heila** [aQute-os/biz.aQute.openapi#9]
When a `$ref` element makes reference to a definition that does not exist in the OpenAPI definition JSON document, it is reported as: 

`ran command or generate but no files were changed; Is `output` correct wrt to the command? : openapi.json;output="src/gen/java/";generate="openapi --output src/gen/java --tags *  --typeprefix MyType --basename OpenAPIBase  --packageprefix org.my.package openapi.json"`

Instead, it should be reported as something like:

`Semantic error at paths./user.post.parameters.0.schema.$ref
$refs must reference a valid location in the document
See line xxx`

Example is taken from [Swagger Editor](https://editor.swagger.io/)

**Comment by pkriens** [comment]
Yes, I need to give the error reporting some love. It sometimes helps to add `>log 2>log` to the command to see the output. But you're right I need to parse the output.

**Comment by pkriens** [comment]
Turns out this is on the bnd side. There is a fix underway.
